### ISSUE TITLE
Sube el archivo!

### ISSUE THREAD

**Issue by jEsuSdA** [antonio-mario/tuduix#1]
Sube el archivo!
Sube el archivo!
Sube el archivo!
Sube el archivo!
Sube el archivo!
....
y, si puedes, sube el archivo!

**Comment by antonio-mario** [comment]
Te lo paso por aquí de momento a tí. Este finde voy a intentar subirlo
guay con git, pero ya lo tienes para echarle un vistazo.

   Acho, y yo pensando que estaba todo subido bien desde el finde pasado y
que os enamoró mi readme, jajajajajaaa
